const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const manifest = JSON.parse(
  fs.readFileSync(path.join(root, "assets/exercises/manifest.json"), "utf8"),
);
const entries = [];
for (const item of manifest) {
  const stem = item.path.replace(/\.jpg$/, "");
  const found = ["jpg", "jpeg", "png", "webp"]
    .map((ext) => `${stem}.${ext}`)
    .find((file) => fs.existsSync(path.join(root, file)));
  if (found)
    entries.push(
      `  ${JSON.stringify(item.id)}: require(${JSON.stringify("../../" + found)}),`,
    );
}
fs.writeFileSync(
  path.join(root, "src/data/imageRegistry.ts"),
  `import type { ImageSourcePropType } from 'react-native';\n\n// Generated by npm run images. Only existing local assets are registered.\nexport const exerciseImages: Record<string, ImageSourcePropType> = {\n${entries.join("\n")}\n};\n`,
);
console.log(
  `Registered ${entries.length} of ${manifest.length} exercise images. Missing images use the built-in placeholder.`,
);
