import type { ImageSourcePropType } from "react-native";

// Generated by npm run images. Only existing local assets are registered.
export const exerciseImages: Record<string, ImageSourcePropType> = {};
